# source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

use_frameworks!

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :preserve_pod_file_structure => true,
         :generate_multiple_pod_projects => true
#         :incremental_installation => true

workspace 'ModuleA.xcworkspace'

target 'ModuleA' do
  
  project 'ModuleA/ModuleA.xcodeproj'
  
  pod 'ModuleARouter', :path => 'ModuleARouter/'
  
end

target 'ModuleARouter' do
  
  project 'ModuleARouter/ModuleARouter.xcodeproj'

  pod 'RaRouter'
  
end
