# source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

use_frameworks!

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :preserve_pod_file_structure => true,
         :generate_multiple_pod_projects => true
#         :incremental_installation => true

workspace 'Global.xcworkspace'

target 'Global' do
  
  project 'Global/Global.xcodeproj'
  
  pod 'GlobalDemoRouter', :path => 'GlobalRouter/'
  
end

target 'GlobalRouter' do
  
  project 'GlobalRouter/GlobalRouter.xcodeproj'

  pod 'RaRouter'
  
end
