# source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

use_frameworks!

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :preserve_pod_file_structure => true,
         :generate_multiple_pod_projects => true
#         :incremental_installation => true

workspace 'Examples.xcworkspace'

target 'Examples' do
  
  project 'Examples/Examples.xcodeproj'
  
  pod 'ExamplesRouter', :path => 'ExamplesRouter/'
  
end

target 'ExamplesRouter' do
  
  project 'ExamplesRouter/ExamplesRouter.xcodeproj'

  pod 'RaRouter'
  
end
