# source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

use_frameworks!

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :preserve_pod_file_structure => true,
         :generate_multiple_pod_projects => true
#         :incremental_installation => true

workspace 'RootController.xcworkspace'

target 'RootController' do
  
  project 'RootController/RootController.xcodeproj'
  
  pod 'RootControllerRouter', :path => 'RootControllerRouter/'
  
end

target 'RootControllerRouter' do
  
  project 'RootControllerRouter/RootControllerRouter.xcodeproj'

  pod 'RaRouter'
  
end
